---
- name: Configure Linux host
  hosts: all
  gather_facts: true
  become_method: ansible.builtin.sudo
  debugger: never
  roles:
    - role: guest-agents
    - role: updates
    - role: desktop
      when: desktop_env
    - role: network
    - role: fixes
      # vars:
      #   virtio_driver_directory: 2k22
      #   virtio_win_iso_path: "F:\\"
      #   spice_tools_uri: "https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe"
    # - base
    # - configure
